name: 'Create a development build on prerelease'

on:
  workflow_call:
    inputs:
      composer:
        default: true
        type: boolean
      npm:
          default: true
          type: boolean
      php:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Load Composer cache...
        if: inputs.composer == true
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer

      - name: Load NPM cache...
        if: inputs.npm == true
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm

      - name: Install Composer...
        if: inputs.composer == true
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM...
        if: inputs.npm == true
        run: npm install

      - name: Run Laravel Mix...
        if: inputs.npm == true
        run: npm run dev

      - name: Package build...
        run: zip -rq9 ${{ github.ref_name }}.zip . -x '.git/*' -x 'node_modules/*'

      - name: Save build artifact...
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}
          path: ${{ github.ref_name }}.zip
          retention-days: 7
