name: 'Run code coverage whenever code is pushed'

on:
  workflow_call:
    inputs:
      xdebug:
        default: false
        type: boolean
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          coverage: xdebug

      - name: Install XDebug...
        if: inputs.xdebug == false
        run: sudo apt-get install php${{ inputs.php }}-xdebug

      - name: Install Composer...
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create code coverage report
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover clover.xml

      - name: Create code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/code-coverage.svg
          push_badge: false

      - name: Push code coverage badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: repo-badges
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
