name: 'Run code coverage whenever a pull request is opened'

on:
  workflow_call:
    inputs:
      artisan:
        default: true
        type: boolean
      xdebug:
        default: false
        type: boolean
      composer:
        default: true
        type: boolean
      env:
        default: true
        type: boolean
      npm:
        default: true
        type: boolean
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number
      vite:
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer...
        if: inputs.composer == true
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Show dir
        run: pwd

      - name: Install NPM...
        if: inputs.npm == true
        run: npm install

      - name: Create .env...
        if: inputs.env == true
        run: cp .env.example .env

      - name: Generate key...
        if: inputs.env == true
        run: php artisan key:generate

      - name: Run Vite...
        if: inputs.npm == true && inputs.vite == true
        run: npm run build

      - name: Run Laravel Mix...
        if: inputs.npm == true && inputs.vite == false
        run: npm run prod

      - name: Run XDebug...
        if: inputs.xdebug == false
        run: npm run coverage

      - name: Create code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}