##RECOMMENDATION - REFERENCED IN PRE-COMMIT/PRE-PUSH - ECR - FEATURE/CODE-COVERAGE
name: 'Create a code coverage badge for main'

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer...
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create code coverage report
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover clover.xml

      name: Coverage percentage
      uses: sergiy-decima/clover-coverage-action@1.0.0
        id: percentage
        if: always()
        with:
        filename: clover.xml >> $GITHUB_OUTPUT

      name: test output
       run: echo "${{steps.Coverage_percentage.output}}" ${{steps.Coverage_percentage.output}}

      - name: Update badge percentage
        run: sed -i "s/$current-coverage/$new-coverage/g" public/images/code-coverage.svg

      - name: Update badge colour based on percentage
        run: |
        if ($new-coverage < 40) {
              $new-color = '#e05d44'; #Red
        } elseif($new-coverage < 60) {
            $new-color = '#fe7d37';  #Orange
        } elseif($new-coverage < 75) {
            $new-color = '#dfb317';  #Yellow
        } elseif($new-coverage < 90) {
           $new-color = '#a4a61d';  #Yellow-Green
        } elseif($new-coverage < 95) {
            $new-color = '#97CA00';  #Green
        } elseif ($new-coverage <= 100) {
            $new-color = '#4c1';     #Bright Green
        }

        sed -i "s/$current-color/$new-color/g" public/images/code-coverage.svg

      - name: commit badge changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "updated code coverage badge"
          git push
