##RECOMMENDATION - REFERENCED IN PRE-COMMIT/PRE-PUSH - ECR - FEATURE/CODE-COVERAGE
name: 'Create a code coverage badge for main'

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer...
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Update badge
        run: |
          sed -i "s/41/99/g" /public/images/code-coverage.svg
          git add -A
          git commit -m "updated code coverage badge"
          git push

        #sed -i
        #if ($coverage < 40) {
        #$color = '#e05d44';  // Red
    #} elseif($coverage < 60) {
     # $color = '#fe7d37';  // Orange
   # } elseif($coverage < 75) {
    #  $color = '#dfb317';  // Yellow
   # } elseif($coverage < 90) {
     # $color = '#a4a61d';  // Yellow-Green
    #} elseif($coverage < 95) {
    #  $color = '#97CA00';  // Green
   # } elseif ($coverage <= 100) {
     # $color = '#4c1';     // Bright Green
   # }
        #if number over a particular change colour

#      - name: Create code coverage report
#        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover clover.xml
#
#      - name: Coverage percentage
#        uses: sergiy-decima/clover-coverage-action@1.0.0
#        if: always()
#        with:
#          filename: clover.xml