##RECOMMENDATION - REFERENCED IN PRE-COMMIT/PRE-PUSH - ECR - FEATURE/CODE-COVERAGE
name: 'Create a code coverage badge for main'

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer...
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create code coverage report
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover clover.xml

      - name: Update coverage badge
        run: |
          set -e
          
          export new_percent=$(vendor/bin/coverage-check ./clover.xml 75 --only-percentage)
          
          export current_percent=$(sed -n 18p public/images/code-coverage.svg|grep -i -o -E [[:digit:]]+%)
          
          export current_color=$(sed -n 12p public/images/code-coverage.svg|grep -i -o "#.*"|sed 's/".*//')
          
          if [ ${new_percent%.*} -eq ${current_percent%?} ]
          then
          echo "Nothing to update"
          exit 0
          else
          sed -i -e "18,19s/$current_percent/${new_percent%.*}%/g" public/images/code-coverage.svg
          fi
          
          if [ ${new_percent%.*} -lt 40 ]
          then
            sed -i -e "s/$current_color/#e05d44/g" public/images/code-coverage.svg
          elif [ ${new_percent%.*} -lt 60 ]
          then
            sed -i -e "s/$current_color/#fe7d37/g" public/images/code-coverage.svg
          elif [ ${new_percent%.*} -lt 75 ]
          then
            sed -i -e "s/$current_color/#dfb317/g" public/images/code-coverage.svg
          elif [ ${new_percent%.*} -lt 90 ]
          then
            sed -i -e "s/$current_color/#a4a61d/g" public/images/code-coverage.svg
          elif [ ${new_percent%.*} -lt 95 ]
          then
            sed -i -e "s/$current_color/#97CA00/g" public/images/code-coverage.svg
          elif [ ${new_percent%.*} -le 100 ]
          then
            sed -i -e "s/$current_color/#4c1/g" public/images/code-coverage.svg
          else
            sed -i -e "s/$current_color/#0a0a0a/g" public/images/code-coverage.svg
          fi

      - name: commit and push badge
        run: |
          set -e
          
          if [[ ${{ github.event.before }} !== ${{ github.event.after }} ]]
          then
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/images/code-coverage.svg
          git commit -m "updated code coverage badge"
          git push
          else
          echo "Nothing to push"
          exit 0
          fi
