name: 'Run tests whenever a pull request is opened'

on:
  workflow_call:
    inputs:
      artisan:
        default: true
        type: boolean
      composer:
        default: true
        type: boolean
      env:
        default: true
        type: boolean
      npm:
        default: true
        type: boolean
      php:
        required: true
        type: string
      timeout:
        default: 5
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer...
        if: inputs.composer == true
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM...
        if: inputs.npm == true
        run: npm install

      - name: Create .env...
        if: inputs.env == true
        run: cp .env.example .env

      - name: Generate key...
        if: inputs.env == true
        run: php artisan key:generate

      - name: Run Laravel Mix...
        if: inputs.npm == true
        run: npm run prod

      - name: Run unit tests...
        run: |
          suites=( $(php ./vendor/bin/phpunit --list-suites | grep -) )

          for suite in ${suites[@]}
          do
            if [ $suite = "-" ]
            then
              continue
            fi
          
            echo "Running PHPUnit for the $suite test suite..."
          
            if [ ${{ inputs.artisan }} = true ]
            then
              php artisan test --parallel --testsuite $suite
            else
              php ./vendor/bin/phpunit --testsuite $suite
            fi
          done
